Repository efshaperveen/MindJournal, pull requests merged in 2025-08, with the labels that each got.

#81 feat: add mood heatmap with color legend and tooltip
  package-lock.json
  package.json
  src/App.css
  src/components/dashboard/Heatmap.jsx
  src/index.css
  src/pages/Dashboard.jsx
Labels: level 3, GSSOc'25

#90 Real time AI assistant helping User to write
  package-lock.json
  src/components/journal/EntryForm.jsx
Labels: level 3, GSSOc'25

#91 Improve heatmap responsiveness and tooltip fixes
  src/components/dashboard/Heatmap.jsx
  src/index.css
Labels: level1, GSSOc'25

#96 Issue #89 fixed
  package-lock.json
  package.json
  src/pages/Calendar.jsx
  src/pages/Settings.jsx
  src/pages/Stats.jsx
Labels: level 2, gssoc2025

#102 Added hand animation in responsive way #95 #99
  src/pages/Dashboard.jsx
Labels: level 1, gssoc2025

#109 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: level 1, gssoc2025

#111 Update README.md to reflect current features (Resolves #107)
  README.md
  public/demo-screenshot.png.png
  public/demo1.jpg
  public/demo2.jpg
  public/demo3.jpg
  public/demo4.jpg
Labels: level 3, gssoc2025

#113 🚀 Add Contact Page with EmailJS Integration & Themed UI ✉
  package-lock.json
  package.json
  src/App.jsx
  src/components/navigation/MobileMenu.jsx
  src/components/navigation/Sidebar.jsx
  src/pages/Contact.jsx
Labels: level 2, gssoc2025
