Repository efshaperveen/MindJournal, pull requests merged in 2025-07, with the labels that each got.

#14 Multi-Select Mood Filter Dropdown with Emoji & Animation
  src/pages/Journal.jsx
Labels: enhancement, level2, GSSOc'25

#25 Add License and Update README
  LICENSE
  README.md
Labels: level2, GSSOc'25

#30 Improve README.md with Structured Format
  README.md
Labels: level2, GSSOc'25

#39 Integrate AI Chatbot Feature in MindJournal
  .gitignore
  README.md
  backend/package-lock.json
  backend/package.json
  backend/routes/mindbot.js
  backend/server.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/navigation/Sidebar.jsx
  src/pages/MindChat.jsx
Labels: level 3, GSSOc'25

#37 feature: Integrated Google oauth for streamlined authentication
  .gitignore
  package-lock.json
  package.json
  src/contexts/AuthContext.jsx
  src/main.jsx
  src/pages/EntryDetail.jsx
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: level 3, GSSOc'25

#42 📚 Added CODE_OF_CONDUCT.md [Closes #36]
  CODE_OF_CONDUCT.md
Labels: level2, GSSOc'25

#44 Download Entry as PDF
  netlify.toml
  package-lock.json
  package.json
  src/App.jsx
  src/components/journal/EntryPDF.jsx
  src/pages/EntryDetail.jsx
Labels: level 3, GSSOc'25

#54 Added show/hide functionality in login and register pages
  src/pages/Login.jsx
  src/pages/Register.jsx
Labels: level1

#63 Feature: Context-Aware AI ChatBot for Journal Entries
  backend/package-lock.json
  backend/package.json
  backend/routes/mindbot.js
  backend/server.js
  src/components/journal/EntryCard.jsx
  src/components/journal/EntryForm.jsx
  src/contexts/JournalContext.jsx
  src/layouts/MainLayout.jsx
  src/pages/MindChat.jsx
  src/pages/MindChatFloat.jsx
Labels: level 3

#65 done feature enhancements
  src/App.jsx
  src/components/dashboard/AffirmationBanner.jsx
  src/components/journal/EntryCard.jsx
  src/components/journal/EntryForm.jsx
  src/components/navigation/MobileMenu.jsx
  src/components/navigation/Sidebar.jsx
  src/data/Quotes.js
  src/pages/Journal.jsx
Labels: level 3, GSSOc'25

#69 [PULL REQUEST] - Font Styling and Consistency Fix (ISSUE #50)
  src/components/calendar/SidePanel.jsx
  src/components/dashboard/AffirmationBanner.jsx
  src/components/dashboard/MoodTracker.jsx
  src/components/dashboard/MoodTrendChart.jsx
  src/components/dashboard/RecentEntries.jsx
  src/components/journal/EntryCard.jsx
  src/components/journal/EntryForm.jsx
  src/components/journal/EntryPDF.jsx
  src/components/loader/QuotesLoader.jsx
  src/components/navigation/MobileHeader.jsx
  src/components/navigation/MobileMenu.jsx
  src/components/navigation/Sidebar.jsx
  src/index.css
  src/pages/Calendar.jsx
  src/pages/CreateEntry.jsx
  src/pages/Dashboard.jsx
  src/pages/EditEntry.jsx
  src/pages/EntryDetail.jsx
  src/pages/ForgotPassword.jsx
  src/pages/Journal.jsx
  src/pages/Login.jsx
  src/pages/MindChat.jsx
  src/pages/Register.jsx
  src/pages/Settings.jsx
  src/pages/Stats.jsx
  tailwind.config.js
Labels: level2, GSSOc'25
